# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.cache/wt [current_project]
set_property parent.project_path F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/COD/lab6/inst_rom.coe
read_verilog -library xil_defaultlib {
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/ALU.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/ALU_Operands.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/ALU_control.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/ALU_out.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/DCU.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/IRnMDR.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/MEM.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/PC.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/PC1.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/RF.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/RFout_AB.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/cache.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/cache_memory_module.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/con_IR_RF.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/control_unit.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/cpu.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/cur_data.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/display_word.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/seg.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/word_dictionary.v
  F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/new/DDU.v
}
read_ip -quiet F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all f:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/constrs_1/imports/lab5/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.srcs/constrs_1/imports/lab5/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top DDU -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DDU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DDU_utilization_synth.rpt -pb DDU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
