webtalk_init -webtalk_dir F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.sim/sim_1/behav/xsim/xsim.dir/ddu_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May 31 21:07:22 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5b135b1b-d7a5-4048-a345-bbc9f6a4efe2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ec90331b1a4f487e8989cb5a9ab326b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "235" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "700 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9440_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2754946500 -regid "" -xml F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.sim/sim_1/behav/xsim/xsim.dir/ddu_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.sim/sim_1/behav/xsim/xsim.dir/ddu_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/COD/lab6/MUL_MIPS_CPU_cache_vga/MUL_MIPS_CPU.sim/sim_1/behav/xsim/xsim.dir/ddu_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
