# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/COD/lab4/paintboard/paintboard.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/COD/lab4/paintboard/paintboard.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/COD/lab4/paintboard/paintboard.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/COD/lab4/paintboard/paintboard.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
